### ISSUE TITLE
[Personnel Request]: Change position of Grace Thomson

### ISSUE THREAD

**Issue by get2061** [EpigeneticsExeter/EpigenomicsLabWeb#142]
### Who are you requesting a change for?

Grace Thomson - PhD student and not PTY student 

### Request type

Make a change to an existing lab member

### Please give us details about the change

Change from PTY student to PhD student

**Comment by sof202** [comment]
Thank you! I will change this later today. Could you possibly send me a profile picture to use on slack as well?
